### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by tmtkzk0823** [kanata-eng1225/RecordSRM#151]
MVPリリースお疲れ様でした:tada:
下記の視点をもとにレビューいたします。

1. READMEから課題解決する実装がされているか&動いている
2. フレームワークの特性を活かし冗長なコードを書いていないか
3. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか

## READMEから課題解決する実装がされているか&動いている
基本的な部分は実装されているかと思います。
本リリースでは、READMEのその後の機能に記載されている内容をベースに、UIUXを整えてより質の高いアプリケーションにしていきましょう。

## フレームワークの特性を活かし冗長なコードを書いていないか
気になった箇所を挙げたのでご確認ください。
- `app/controllers/stress_records_controller.rb`、`app/controllers/stress_reliefs_controller.rb`がFat Controllerになっているので切り出せそうなメソッドをモデルに寄せましょう。モデルも全体的にFatになってきてしまったらhelperやconcernに寄せて読み込む形がいいと思います。

## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
気になった箇所を挙げたのでご確認ください。
- **オススメのストレス解消法一覧**機能ですが、投稿されたストレス解消方のデータを一覧で出しているかと思いますのでオススメの表記はなくてもいいのかなと思いました。
- また、ランキング機能をまだ実装していない状態でしたら、**ランキング機能→レコメンド機能に変更**し、**ユーザーにあったストレス解消法をお勧めしてくれる機能**を作成すると、アプリの方向性もあっていて、技術をさらに上乗せできると思いました。（ランキング機能のリンクがある場所にレコメンドしてくれる機能を発火（もしくはページ遷移）するリンクに置き換えるイメージです。ランキング機能をすでに実装していただいている場合はそのまま大丈夫です。）
- 一覧機能にストレス解消法をカードで表示していると思うのですが、カード全体がリンクになっていて、いいねやタグの検索が詳細ぺージからしかできない状態ですので、カードからもコチラの機能を使えるといいかなと思いました。
- また、上記に付随して一覧ページから、タグ、難易度別での絞り込みができてもいいと思います。
- 画像が自動で設定される機能ですとタイトルや内容と画像が乖離のある投稿に見えてしまうので、ファイルアップロードの機能を追加するか、タイトルと内容をAIに投げ、AIに画像を作ってもらいそちらを反映させても面白いアプリになるかなとも思いました。

#### 以上です！

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。
また書き出したissueをもとに修正完了までのスケジュールを教えていただけますでしょうか？
よろしくお願いいたします。

**Comment by kanata-eng1225** [comment]
@tmtkzk0823 
レビューありがとうございます!
いただいた意見を元にissueを作成いたしました。
本リリースは、11月22日を考えています。

**Comment by tmtkzk0823** [comment]
確認しました！
本リリースまで頑張っていきましょう！！
