### ISSUE TITLE
jsファイルが読み込めないです。

### ISSUE THREAD

**Issue by kanata-eng1225** [kanata-eng1225/RecordSRM#43]
- 質問内容・実現したいこと
rating.jsが本番環境で読み込めないので解決したいです。
ローカル環境の検証ではエラーは発生せず、星の難易度機能が正常に動作しています。

　環境
　　IntelMac
　　Ruby:3.2.2
　　Rails:7.0.7
　　Tailwind
　　daisyui
　　PostgreSQL
　　Heroku

- 現状発生している問題・エラーメッセージ
本番環境で以下のエラーとなり星の難易度機能が動作しません。新規投稿画面、編集画面で、マウスでクリックして星の数の変更ができません。

```
GET https://recordsrm-37f72a7e03de.herokuapp.com/assets/rating net::ERR_ABORTED 404 (Not Found)
application-33e668de9c9a56b247354bd802293ac6ade54b335b592846c9976afbfdcf285e.js:4
```

- どの処理までうまく動いているのか
  ローカル環境は動作しています。

- 該当のソースコード
app/javascript/application.js
```
// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "./rating"

```

app/javascript/rating.js
```
document.addEventListener("turbo:load", function() {
  document.querySelectorAll('.star-label').forEach((label, index, labelArray) => {
    label.addEventListener('click', (e) => {
      const radioButton = document.getElementById(`rating_${index + 1}`);
      radioButton.checked = true;

      labelArray.forEach((starLabel, starIndex) => {
        if (starIndex <= index) {
          starLabel.textContent = "★";
          starLabel.classList.remove('text-gray-400');
          starLabel.classList.add('text-yellow-500');
        } else {
          starLabel.textContent = "★";
          starLabel.classList.remove('text-yellow-500');
          starLabel.classList.add('text-gray-400');
        }
      });
    });
  });
});


```

config/importmap.rb
```
# Pin npm packages by running ./bin/importmap

pin "application", preload: true
pin "@hotwired/turbo-rails", to: "turbo.min.js", preload: true
pin "@hotwired/stimulus", to: "stimulus.min.js", preload: true
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js", preload: true
pin_all_from "app/javascript/controllers", under: "controllers"
pin "rating", to: "app/javascript/rating.js"

```

- エラーから考えられる原因
assetsにratingファイルが無いので、エラーが発生していると考えられる。

- 試したこと
1.記事を参考にconfig/importmap.rbに```pin "rating", to: "app/javascript/rating.js"```を追加してデプロイしました。
2.```heroku run rails assets:precompile```を実行しました。

**Comment by Tsuchiya2** [comment]
情報が少ないため精度の低い回答になることをご了承ください。

```
GET https://recordsrm-37f72a7e03de.herokuapp.com/assets/rating net::ERR_ABORTED 404 (Not Found)
application-33e668de9c9a56b247354bd802293ac6ade54b335b592846c9976afbfdcf285e.js:4
```

上記のエラー内容からassetsを呼び出そうとしているものの、ファイルが無いのでエラーになっているのは仰っているとおりかと思います。

公式がCDNなどを用意していないかetc、確認してみて必要なファイルを読み込ませるようにしてあげると解消しそうですが、何が不足しているか調べたり仮説検証してみてください。

---

■ChatGPTの回答

GET https://recordsrm-37f72a7e03de.herokuapp.com/assets/rating net::ERR_ABORTED 404 (Not Found) というエラーは、Herokuの本番環境が rating.js ファイルを見つけられないという問題を指しています。

以下はいくつかの解決策です。

1. importmapの確認
config/importmap.rb ファイルが正確に設定されているか確認してください。特にパスが正しいかどうか注意深く確認してください。

2. Herokuにデプロイされたファイルの確認
Herokuのコンソールまたはターミナルを使って、デプロイされたアプリケーションに rating.js が正確にアップロードされているか確認してください。

```
heroku run bash
````

# アプリケーションのディレクトリに移動して

```
ls app/javascript/
```

3. アセットプリコンパイルの確認
heroku run rails assets:precompile を実行する前に、以下のコマンドで一旦既存のコンパイル済みアセットを削除してみてください。

```
heroku run rails assets:clobber
````

その後、再度 assets:precompile を実行してデプロイしてみてください。

4. アプリケーションログの確認
Herokuのアプリケーションログにエラーや警告がないか確認してください。

```
heroku logs --tail
```

5. ブラウザのコンソールログ
ブラウザのデベロッパーツールを開いて、コンソールに何かエラーメッセージが表示されていないか確認してください。

以上のいずれか（または複数）が問題の解決につながる可能性があります。順番に試して、どれが効果的か確認してみてください。

**Comment by kanata-eng1225** [comment]
以下の記事を参考にした所、本番環境でも動作しました。
https://stackoverflow.com/questions/70548841/how-to-add-custom-js-file-to-new-rails-7-project

修正したファイルは以下です。
app/javascript/application.js
```
// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "custom/rating"

```
app/javascript配下にcustomフォルダを作成
```app/javascript/rating.js```を```app/javascript/custom```に移動

config/importmap.rb
```
# Pin npm packages by running ./bin/importmap

pin "application", preload: true
pin "@hotwired/turbo-rails", to: "turbo.min.js", preload: true
pin "@hotwired/stimulus", to: "stimulus.min.js", preload: true
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js", preload: true
pin_all_from "app/javascript/controllers", under: "controllers"
pin_all_from "app/javascript/custom", under: "custom"

```

**Comment by Tsuchiya2** [comment]
良かったです。引き続き頑張ってくだ愛。
